### ISSUE TITLE
Json schema linting in CI

### ISSUE THREAD

**Issue by danihengeveld** [DependencyTrack/helm-charts#104]
It would be great if we could verify the value files against the json schema in CI.

This would enforce an up-to-date schema file for every change made to the charts.

Instead of creating an action for this ourselves I would recommend picking up this existing issue for the Validate Json Action first. When closed we can just use this.

https://github.com/OrRosenblatt/validate-json-action/issues/26

**Comment by nscuro** [comment]
JSON schema validation is already part of `helm lint` and `helm install`, you can see a validation failure during `lint` here: https://github.com/DependencyTrack/helm-charts/actions/runs/9599633812/job/26473974378

Is there anything beyond this that you'd like to see?

**Comment by danihengeveld** [comment]
Oh, I was completely unaware of this, but that is a welcome surprise. Apologies.

Nothing else I can think of for now.
