### ISSUE TITLE
Deployment failing with digest in image tag 

### ISSUE THREAD

**Issue by davidr-bgp** [DependencyTrack/helm-charts#111]
The image tag of apiServer and frontend is used as direct input their respective label `app.kubernetes.io/version`.

When pinning the image tag to a specific sha256 digest, the maximum length of the label is exceeded and deployment fails.

Relevant lines: [_helpers.tpl L56](https://github.com/DependencyTrack/helm-charts/blob/f04cbb3e54399ab8ec379068bc30d748c9a6293f/charts/dependency-track/templates/_helpers.tpl#L56), [_helpers.tpl L96](https://github.com/DependencyTrack/helm-charts/blob/f04cbb3e54399ab8ec379068bc30d748c9a6293f/charts/dependency-track/templates/_helpers.tpl#L96).

As a quick workaround I use `.Chart.AppVersion`, not `.image.tag`.
I’m not sure what a better solution would be.

**Comment by nscuro** [comment]
Truncation is the only way forward here. So we need to do something similar to what we do for `name` and `fullname`:

https://github.com/DependencyTrack/helm-charts/blob/79745463f35286a2634a17155d6e808eaa6e448f/charts/dependency-track/templates/_helpers.tpl#L1-L24
