### ISSUE TITLE
Prometheus Operator invalid configuration

### ISSUE THREAD

**Issue by 98jan** [DependencyTrack/helm-charts#182]
Hi,

I installed the helm chart of dependency-track in my running Kubernetes Cluster with a preconfiugred kube-prometheus-stack and the serviceMonitorof dependency-track is rejected, because the scapeTimeout is higher then the scrapeInterval, see following log message:

`ts=2024-11-03T14:19:26.716949381Z level=info caller=/home/runner/go/pkg/mod/k8s.io/client-go@v0.31.1/tools/record/event.go:389 msg="Event occurred" object.name=dependency-track-api-server object.namespace=dependency-track fieldPath="" kind=ServiceMonitor apiVersion=monitoring.coreos.com/v1 type=Warning reason=InvalidConfiguration message="ServiceMonitor dependency-track-api-server was rejected due to invalid configuration: scrapeTimeout \"30s\" greater than scrapeInterval \"15s\""`

I would propose to either increase scrape interval to 30s or reduce scrapeTimeout to 15s that no issues with the prometheus-operator arise.

**Comment by nscuro** [comment]
Fixed via #181
