### ISSUE TITLE
Issue connecting to internal database.

### ISSUE THREAD

**Issue by numa1985** [DependencyTrack/helm-charts#64]
Hi ,

Pod is going for crashloopback due to issue connecting to database.
We are using AKS with Kubernetes version 1.29.2.PFB details.

ubuntu@NARU-Pr5530:~/dtrack$ helm upgrade --install dtrack dependency-track/dependency-track --namespace dtrack --reset-values --values values.yaml
Release "dtrack" has been upgraded. Happy Helming!
NAME: dtrack
LAST DEPLOYED: Wed May 22 11:38:49 2024
NAMESPACE: dtrack
STATUS: deployed
REVISION: 2
TEST SUITE: None

ubuntu@NARU-Pr5530:~/dtrack$ cat values.yaml
apiServer:
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
  persistentVolume:
    enabled: true
    size: 10Gi
  extraEnv:
    SYSTEM_REQUIREMENT_CHECK_ENABLED: "false"

Error info
++++
![image](https://github.com/DependencyTrack/helm-charts/assets/139448875/3f4611e6-73d0-492c-b747-df108532de96)

Thanks

**Comment by nscuro** [comment]
You need to ensure that the API server process is permitted to read and write files from and to the persistent volume, where both logs and the embedded database are stored. 

The `values.yaml` has an example on how to achieve that via `initContainers`:

https://github.com/DependencyTrack/helm-charts/blob/15d97536949354f5644fd879a4e51ae1bb83d6d4/charts/dependency-track/values.yaml#L76-L95

**Comment by numa1985** [comment]
@nscuro : Thanks .. It worked was able to connect to internal database,but for production we are planning to use microsoftSQLServer database,if we want to add the below details under api server where should we add.

![image](https://github.com/DependencyTrack/helm-charts/assets/139448875/17b67cee-b8e2-4c85-905e-8684ecb32c52)

**Comment by nscuro** [comment]
See https://docs.dependencytrack.org/getting-started/configuration/#api-server

If properties are specified as `foo.bar.baz`, their respective environment variable would be `FOO_BAR_BAZ`.

Example with MSSQL: https://github.com/DependencyTrack/dependency-track/blob/b188c7d919d7fc9568dde86d3e5a29a05ad6f66c/dev/docker-compose.mssql.yml#L23-L27

Closing this issue as the original problem has been resolved.
