### ISSUE TITLE
Dependency-Track requires a minimum of 2 CPU cores. Cannot continue. To fix, specify -Xmx4G (or higher) when executing Java.

### ISSUE THREAD

**Issue by Michenux** [DependencyTrack/helm-charts#78]
I have the error : 

> Dependency-Track requires a minimum of 2 CPU cores. Cannot continue. To fix, specify -Xmx4G (or higher) when executing Java.

My kubernetes nodes have only 2 CPU at this time and i would like to make it work with that configuration for testing.

In values.yml : 

```yaml
apiServer:
  extraEnv:
    EXTRA_JAVA_OPTIONS: -Xmx4G
```

I have tried with simple quotes, double quotes and no quote for the value. Always this error.

**Comment by nscuro** [comment]
You can disable the requirements check via environment variable, that's also what we do for the chart's CI tests:

https://github.com/DependencyTrack/helm-charts/blob/2f1ea1add121b3638cadd4ca17a4cd1d1c6240cf/charts/dependency-track/ci/test-values.yaml#L5-L14

I just realized the error message is misleading. Tweaking the heap size (`-Xmx`) will not help for CPU resources. Will tweak the message for the upcoming release.

**Comment by Michenux** [comment]
It's ok for me, thanks a lot.
