### ISSUE TITLE
apiServer Deployment

### ISSUE THREAD

**Issue by theartusz** [DependencyTrack/helm-charts#81]
Hi folks,

currently, the official Helm chart for DT contains only `StatefulSet`  deployment option for `apiServer`. Is it planned to support also `Deployment` option for those who have databse running outside of the k8s cluster?

I could think there would be a flag `{{- if .Values.apiserver.deploymentType.deployment-}}` in the `deployment` template which will decide which deployment type would be used - `StatefulSet` or `Deployment`.

I was thinking the `Ddeployment` manifest could be inspired by the [evryfs-oss heln chart](https://artifacthub.io/packages/helm/evryfs-oss/dependency-track?modal=template&template=backend/deployment.yaml)

What does the community think about that?

**Comment by nscuro** [comment]
Open to changing that.

For background, there's more than just the database that makes the API server stateful: https://docs.dependencytrack.org/getting-started/data-directory/

**Comment by theartusz** [comment]
Maybe a stupid question, but how do I become a contributor? I have never committed to open source project.
I made a draft yesterday and would like review for it.

**Comment by nscuro** [comment]
GitHub has a good guide on how to do it: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

Happy to help if you run into any challenges.

**Comment by theartusz** [comment]
I have made pull request: https://github.com/DependencyTrack/helm-charts/pull/102 
I am not sure if you guys have a template for PR description. The other open PR has quite more extensive description.
